version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce_web
    # Use the host's network. This allows the container to connect to
    # services on the host machine using 'localhost'.
    network_mode: "host"
    command: sh -c "chmod +x /app/entrypoint.sh && /app/entrypoint.sh gunicorn --bind 0.0.0.0:8000 eCommerce.wsgi:application"
    volumes:
      - ./eCommerce:/app
      - ./entrypoint.sh:/app/entrypoint.sh
    env_file:
      - eCommerce/.env
